### ISSUE TITLE
[BUG] panic: runtime error: invalid memory address or nil pointer dereference with lino-toolbox:1.4.0

### ISSUE THREAD

**Issue by pbq** [CGI-FR/LINO-toolbox#17]
Got this error while running a lino push command with lino-toolbox:1.4.0 on an oracle 19 database table.

the command
`lino pull ${SOURCE} --table ${TABLE} -l 0 | lino -v 3 push truncate --table ${TABLE} ${DESTINATION} -e error-ref-${TABLE}.json`

the stacktrace
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa01ab0]
goroutine 1 [running]:
github.com/cgi-fr/lino/internal/infra/push.OracleDialect.ConvertValue({}, {0xad6de0?, 0xc0006800c0?}, {{0xc00012a1f8, 0x8}, 0x0, {0x0, 0x0}})
	/workspace/internal/infra/push/datadestination_oracle.go:185 +0x70
github.com/cgi-fr/lino/internal/infra/push.(*SQLRowWriter).Write(0xc0004a2180, 0xc00068a1b0, 0xc0000b4140?)
	/workspace/internal/infra/push/datadestination_sql.go:345 +0x2ea
github.com/cgi-fr/lino/pkg/push.pushRow(0x42f7b0?, {0xcde350, 0xc0003c30e0}, {0xcdf300, 0xc0000b4140}, {0xcddb60, 0xc00005a4e0}, 0x0, {0xcd9eb8, 0xc000120980}, ...)
	/workspace/pkg/push/driver.go:224 +0x3df
github.com/cgi-fr/lino/pkg/push.Push({0xcde318, 0xc00005a510}, {0xcde350, 0xc0003c30e0}, {0xcddb60, 0xc00005a4e0}, 0x0?, 0x1f4, 0x0?, {0xcd7000, ...}, ...)
	/workspace/pkg/push/driver.go:70 +0x2e5
github.com/cgi-fr/lino/internal/app/push.NewCommand.func3(0xc0003cd500?, {0xc00013d280, 0x2, 0x8?})
	/workspace/internal/app/push/cli.go:155 +0x845
github.com/spf13/cobra.(*Command).execute(0xc0003cd500, {0xc00013d200, 0x8, 0x8})
	/home/vscode/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x1da1640)
	/home/vscode/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x425
github.com/spf13/cobra.(*Command).Execute(...)
	/home/vscode/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.main()
	/workspace/cmd/lino/main.go:138 +0x25
```

was working with lino-toolbox:1.2.0 and 1.3.0

**Comment by youen** [comment]
Thank you @pbq for reporting the issue. We've created a ticket in the Lino project. Can you let me know if the Lino command fails right away or if it manages to process a certain number of lines before failing? Also, could you please run the command `lino table extract ${source}` and provide us with the `table.yaml` file?

**Comment by pbq** [comment]
Hi @youen, the lino command fails on the first pushed line. 
i will extract the tables as soon as possible.

**Comment by pbq** [comment]
My database has approximately 700 tables, do you need the full extraction or only the table to fail's description ?

**Comment by Chao-Ma5566** [comment]
Hello @pbq , I've been assigned to fix this bug. Only the tables in the failure's description seem perfect. I suspect the bug is occurring because the table's `descriptor.column` is nil.

**Comment by pbq** [comment]
hello @Chao-Ma5566, here is the previous extract i used to use with lino
```yaml
version: v1
tables:
  - name: ADPJPAC
    keys:
      - LECTEUR
      - MATRI
      - DAT
      - HEURE
      - SECONDES
```

and here is the fresh extract with `lino talbe extract ${my_source}`
```
version: v1
tables:
  - name: ADPJPAC
     keys:
        - MATRI
        - DAT
        - HEURE
        - LECTEUR
        - SECONDES
      columns:
        - name: MATRI
          export: string
        - name: DAT
          export: datetime
        - name: HEURE
          export: string
        - name: LECTEUR
          export: string
        - name: TYPEVE
          export: string
        - name: IMPUT
          export: string
        - name: SECONDES
          export: string
        - name: SENS
          export: string
        - name: MODLEC
          export: string
        - name: BADGE
          export: string
        - name: ANOM01
          export: numeric
        - name: ANOM02
          export: numeric
        - name: ANOM03
          export: numeric
        - name: ANOM04
          export: numeric
        - name: STATUS
          export: string
        - name: INSTANCE
          export: string
        - name: COORDLAT
          export: string
        - name: COORDLONG
          export: string
        - name: TOLERANCE
          export: string
```
